### ISSUE TITLE
Ediff is visually difficult to use in this theme

### ISSUE THREAD

**Issue by pbgc** [srcery-colors/srcery-emacs#1]
Hi,

I really like this theme!
The only thing that I really can't use is ediff! The bold red/green gets completely lost with all the other reds/greens ...
I would be really better to use (almost standard on other themes) a red/green background on the back of the bolds, to clearly see the current-diff .. 

Thanks for your great work!
Pedro Costa

**Comment by roosta** [comment]
Hi, thanks for using srcery. I've pushed a potential fix on the develop branch, could you check it out and see if it works better for you?

**Comment by pbgc** [comment]
Hi again!

THANKS for your quick answer reaction!
I tried the branch and it's better! but I would suggest another (very common) change to make it perfect (IMHO, of course).
The idea is that the fine-diff's should have a background too, so it's really visible the changes inside each current-diff! As current-diff is using dark colors background ... fine-diff could use the equivalent colors.
I tried and for me it's perfect (the colors could be other if preferred, but the effect is the right one)

```
@@ -846,19 +846,19 @@
       (,srcery-256-class(:background ,srcery-256-gray1))))
 
    `(ediff-fine-diff-A
-     ((,srcery-class(:weight bold))
+     ((,srcery-class(:background ,srcery-red :weight bold))
       (,srcery-256-class(:weight bold))))
 
    `(ediff-fine-diff-Ancestor
-     ((,srcery-class(:weight bold))
+     ((,srcery-class(:background ,srcery-cyan :weight bold))
       (,srcery-256-class(:weight bold))))
 
    `(ediff-fine-diff-B
-     ((,srcery-class(:weight bold))
+     ((,srcery-class(:background ,srcery-green :weight bold))
       (,srcery-256-class(:weight bold))))
 
    `(ediff-fine-diff-C
-     ((,srcery-class(:weight bold))
+     ((,srcery-class(:background ,srcery-blue :weight bold))
       (,srcery-256-class(:weight bold))))
```

Many thanks again!
Pedro Costa

**Comment by roosta** [comment]
Thanks for the suggestion! I've pushed the change you suggested. Care to try it out before I merge with master?

**Comment by pbgc** [comment]
Just pulled and tried. For me it's great! Thank you!

**Comment by roosta** [comment]
Excellent :) I'm gonna have to rebase this branch so make sure to checkout master or reset the develop branch.
