### ISSUE TITLE
Fringe needs to define a background ?

### ISSUE THREAD

**Issue by gagbo** [srcery-colors/srcery-emacs#2]
I'm still not sure how I'm supposed to develop themes when I pull them from melpa using `use-package`, but if/when I find out I can take care of this.

The fringe face does not define the :background, so the background of the fringe just stays as it was defined.
In this screenshot we can see a deep blue/gray column between cursor and line numbers because that's the background I defined in my .Xresources; but when changing theme from light to dark for example, the background of the fringe will stay white, so white strips are pillarboxing my buffers when I do the switch

![fringe_srcery](https://user-images.githubusercontent.com/10496163/49737809-08eb6400-fc8e-11e8-81b6-048871a6c277.png)

### To reproduce

- `Emacs.background: #FFFFFF` in `~/.Xresources` and merge it.
- Start emacs and `(load-theme 'srcery t)`
- Enable fringes with `M-x fringe-mode RET RET` or `M-: (fringe-mode 1)` if they're not enabled

Now you should have white columns pillarboxing the buffer

**Comment by roosta** [comment]
Added a fix. See commit above. As for developing a theme, what I usually  do is just edit whatever I need in the theme then `m-x load-file` and the changes are active. There is an option in use-package called `:load-path` that could possibly be used to point it to a local location.

**Comment by gagbo** [comment]
Seems good to me !
