### ISSUE TITLE
redefine colors in shell-mode

### ISSUE THREAD

**Issue by parjanya** [srcery-colors/srcery-emacs#4]
Hi!

By evaluating this I made shell-mode to use the theme’s colors:

```
(setq ansi-color-names-vector
      (vector srcery-black         ; "black"
	      srcery-red           ; "red3"
	      srcery-green         ; "green3"
	      srcery-bright-yellow ; "yellow3"
	      srcery-blue          ; "blue2"
	      srcery-magenta       ; "magenta3"
	      srcery-cyan          ; "cyan3"
	      srcery-gray-5        ; "gray90"
	      ))

(setq ansi-color-map (ansi-color-make-color-map))
```
Perhaps it could be added to the theme?

**Comment by roosta** [comment]
Hello :) Theres already an ansi-color-names-vector defined under `custom-theme-set-variables` but they are set to the srcery-256 colors. Are you saying that setting them to your example evals to the correct colors in both term and graphical frames?

**Comment by parjanya** [comment]
I had only tested graphical frames. I don’t quite get how colors change in the terminal, and from my test most of the ones set by that command do appear correct on the term, except the black color weirdly.

![srcery-emacs-1](https://user-images.githubusercontent.com/271865/50549965-00af9480-0c4e-11e9-9837-9ac84dc14f7a.png)

🤔

Anyhow, the colors were the vanilla ones before I added the snippet above.

**Comment by roosta** [comment]
I'm not sure I get it either honestly. I pushed a commit where the colors are set to the GUI color variants and it looks OK here in both terminal and graphical frames. Not sure why your black color it is like it is, its seems OK here.
561d83d5bbd4c1c939ad9f52863e75b969af320d

**Comment by roosta** [comment]
Closing this then
