### ISSUE TITLE
The color of show-paren-match is too dim to distinguish

### ISSUE THREAD

**Issue by BooAA** [srcery-colors/srcery-emacs#5]
As title, I think the color of matching parenthesis in show-paren-mode might be too dim to distinguish. 

![Screenshot from 2019-03-10 16-51-15](https://user-images.githubusercontent.com/32809182/54082692-c7ce2300-4354-11e9-94ee-1e486c1f3966.png)

You can see the last and the last-second parenthesis in line 6 are too similar, which IMHO is hard to recognize. Things go worse if there are multiple parenthesis in same line and  it's very hard to find out the matching parenthesis in a short time. Wish to have a high contrast color.

BTW, thanks for this awesome theme, which is warm, elegant and easy to eye.

**Comment by roosta** [comment]
Thank you for posing an issue and using srcery-emacs :) I've tried a bunch of different variations when it comes to matching paren, never been able to find something that works, that doesn't conflict with something else. I'd be open to suggestions. It's worth noting using [paren-face](https://github.com/tarsius/paren-face) makes it easier to spot the matching paren. There is a face defined in srcery for `paren-face` that dims all other parens to a subtle gray. It's not for everyone and I'd like a solution to this that doesn't require a plugin.

**Comment by roosta** [comment]
Also I entirely agree that the way it is currently is not optimal

**Comment by BooAA** [comment]
I tried paren-face several month ago, but it didn't provide any feature necessary to me since I'm comfortable to a language with lots of parenthesis, I can ignore those parenthesis automatically.

However, show-paren-mode is necessary to me since I judge the scope of current expression by  different reaction of matching parenthesis. Maybe we can highlight the matching parenthesis by underline or something else. (wave, italic slant, box etc)

Currently I overwrite srcery-theme by
```
(set-face-attribute 'show-paren-match nil :foreground "yellow" :underline t)
```
it looks like
![Screenshot from 2019-03-12 14-37-48](https://user-images.githubusercontent.com/32809182/54179689-819fcd80-44d4-11e9-98aa-08ec2ba2b80d.png)

I'm not an expert on color and I admit yellow is a little bit ugly, but it works for me and the underline helps me to point out the matching parenthesis quickly. This is my own advice and experience for you, hope you team can find out the optimal solution soon.

**Comment by roosta** [comment]
Thanks for the feedback, Your proposed solution seems pretty nice to me. My only concern is that underline is also used to denote errors with flycheck, could be confusing. I pushed the change to the `develop` branch. Gonna try it out for a few days before I merge into `master`

**Comment by roosta** [comment]
Turned out that srcery yellow was not a good choice, since it looks a lot like white. I changed it to background magenta, foreground white:
![example](https://user-images.githubusercontent.com/4509009/54536351-da69dd00-4990-11e9-9027-37a498fec8fd.png)
Works for me so far, no issues yet. Let me know if this works for you.
