### ISSUE TITLE
org-mode: showing spelling format over verbatim

### ISSUE THREAD

**Issue by ghost** [srcery-colors/srcery-emacs#8]
In org-mode the verbatim (=) format shows over the spelling one (flyspell), so you can't see if something is spelled wrong.  Inside verbatim, code '\~' already shows over the comment.  So when you highlight '=' (which is orange) and it has '\~' (which is blue) it will show that section as blue.  Anyway to do this for the spelling one too?

**Comment by roosta** [comment]
I'm not entirely sure if that's possible, it seems that is the intended behavior. Words inside source blocks and verbatim is skipped by flycheck. To fix this I think is a configuration issue, not a theme issue.

For reference I found this when doing a quick google search: https://emacs.stackexchange.com/questions/54619/skip-flyspell-checking-of-code-and-verbatim-regions-in-org-mode#54904

**Comment by ghost** [comment]
Thank you for looking at this and that link.  Going off that link, it appears what I wanted was already default but I made a mistake in my configuration.

I guess I didn't do my due diligence when I looked with `emacs -q`.  Sorry for time wasted.
