### ISSUE TITLE
Looking for maintainers and contributors

### ISSUE THREAD

**Issue by roosta** [srcery-colors/srcery-emacs#9]
Currently looking for maintainers/contributors. I've personally moved away from Emacs, I'm available for bug fixes and other minor issues but no more progress is made on this theme unless a new maintainer can be found. 

Comment here if you are interested.

**Comment by kenranunderscore** [comment]
I could help out, though I would probably not "extend" the theme in any sense (as it's following your set of srcery colors). I have an Emacs theme of my own I'm using from time to time (I cycle between themes on a daily basis), and whenever I use or try out a new package I check its styles and add them to my theme. I could do the same here without much additional effort if you're interested.

**Comment by roosta** [comment]
That would be awesome :) I used the same method when developing this theme. It always had its own character and isn't exactly like the vim theme, largely because of that. 

I've sent an invite giving you write access to this repo. Thanks for helping out!

**Comment by ibakepunk** [comment]
Hey @roosta I've just created my own theme for Emacs https://github.com/ibakepunk/helix-theme and In case you need anything done here, I can help with maintaining this one.

**Comment by roosta** [comment]
Hi @ibakepunk, I'd be happy to give you access as long as you coordinate with @kenranunderscore. Appreciate the interest.

**Comment by ibakepunk** [comment]
@roosta got it! Thanks for the invitation! @kenranunderscore if you have anything on your mind that you don't have time/desire to implement, we can have a chat about that and I'll do my best to do it.

**Comment by roosta** [comment]
Think we can close this now, thanks a ton for helping out @kenranunderscore @ibakepunk

**Comment by kenranunderscore** [comment]
Sure thing! @ibakepunk I don't do much in here, basically whenever I stumble upon a new face during normal Emacs usage, I check my own theme and srcery to see if any theme needs an update or tweak :)
